### ISSUE TITLE
ImportError: No module named ui

### ISSUE THREAD

**Issue by truongtamgio** [mko-x/katoolin#4]
Hello,
I install Katoolin in Ubuntu 16.04 LTS in Google Cloud and I got this error:

```
Run katoolin just from terminal e.g. by calling katoolin
Traceback (most recent call last):
  File "/usr/bin/katoolin", line 8, in <module>
    from ui import UI
ImportError: No module named ui

```

How to fix it ? Thank you ;0

**Comment by mko-x** [comment]
Hi @truongtamgio,

first of all thank you for your report.

Please use the issue template.

I need some more information as stated in the template.

Please provide the content of your $PATH variable (e.g. via `echo $PATH`), of the $PYTHON  variable (via `echo $PYTHON`) and finally please export the DEBUG environment variable on the machine (via `export DEBUG=1`) and run katoolin again. Please attach the log output here to the issue.

Don‘t forget to unset DEBUG again if finished (via `unset DEBUG`).

thx,
mko-x

**Comment by truongtamgio** [comment]
Hi,
My Content of $PATH variable:

`/home/docker/bin:/home/docker/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin`

When I type **"echo $PYTHON"**, it shows nothing

I run katoolin again but don't know how to download log output. Where to download it ?

**Comment by mko-x** [comment]
Ok.

What is the output of `which python`?

You might want to have look at [google cloud docs](https://cloud.google.com/python/setup)

**Comment by truongtamgio** [comment]
Hi,
when I type "which python", it showed 

**/usr/bin/python**

**Comment by kwongtn** [comment]
Hi, same issue here. Here are my outputs

123@pop-os:~$ echo $PATH
> /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin

123@pop-os:~$ echo $PYTHON
>

123@pop-os:~$ export DEBUG=1
>

123@pop-os:~$ katoolin
>Traceback (most recent call last):
  File "/usr/bin/katoolin", line 8, in <module>
    from ui import UI
ImportError: No module named ui

123@pop-os:~$ unset DEBUG
>

123@pop-os:~$ which python
>/usr/bin/python

**Comment by mko-x** [comment]
@kwongtn - Thank you for your logs. 

I have a fix in the pipeline. Try to update this week, just need some tests.

**Comment by DimitrisPr** [comment]
I remember that issue as well. I think it happened right after the completion of #3 . Not sure though.

**Comment by mko-x** [comment]
Sorry, my fault - working on a more stable release right now.

**Comment by mko-x** [comment]
New version fixes the "ImportError: No module named ui" - besides other improvements.

Please try [CopperBird (2.1.0)](https://github.com/mko-x/katoolin/releases/tag/2.1.0).

Report any errors here at [issues](https://github.com/mko-x/katoolin/issues).

**Comment by DimitrisPr** [comment]
**Manually** downloading and extracting the zip file and installing katoolin works good.

Though CLI/Terminal installation now fails with this message

`wget https://git.io/fjf6m -O katoolin.zip
unzip katoolin.zip
sudo ./install.sh
katoolin`

**Error**
`Archive:  katoolin.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of katoolin.zip or
        katoolin.zip.zip, and cannot find katoolin.zip.ZIP, period.`


At last but not least, I believe that #3 is still open because
Katoolin is still _unable to locate_ most of the packages.

e.g
`E: Unable to locate package ace-voip
E: Unable to locate package amap
E: Unable to locate package automater`

**Comment by mko-x** [comment]
Yeah well - the idea of managing the kali tools by hard code isn't working. Almost every other day there are tools disappearing, renaming, updating etc.

I will probably close this project as not maintainable.
